[package]
name    = "ncollide"
version = "0.6.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

description = "2 and 3-dimensional collision detection library in Rust."
documentation = "http://ncollide.org/doc/ncollide"
homepage = "http://ncollide.org"
repository = "https://github.com/sebcrozet/ncollide"
readme = "README.md"
keywords = [ "collision", "geometry", "distance", "ray", "convex" ]
license = "BSD-3-Clause"

include = [
    "src/**/*.rs",
    "benches/**/*.rs",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]

[lib]
name = "ncollide"
path = "src/lib.rs"

[dependencies.ncollide_math]
path = "ncollide_math"
[dependencies.ncollide_entities]
path = "ncollide_entities"
[dependencies.ncollide_queries]
path = "ncollide_queries"
[dependencies.ncollide_pipeline]
path = "ncollide_pipeline"
[dependencies.ncollide_procedural]
path = "ncollide_procedural"
[dependencies.ncollide_transformation]
path = "ncollide_transformation"
[dependencies.ncollide_utils]
path = "ncollide_utils"

[dev-dependencies]
nalgebra = "*"
rand = "*"
